version: "3.8"

services:
  flask-app:
    build: 
      context: .
      args:
        FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}  # Assuming this variable is in your environment or .env file
    container_name: flask-app 
    ports:
      - "80:80"
    environment:
      - FLASK_ENV=development
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
    volumes:
       - .:/usr/src/app
       - /usr/src/app/__pycache__
